### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [secureprivacy/secureprivacyai-gtm-template#1]
https://github.com/secureprivacy/secureprivacyai-gtm-template/blob/392f03eef94246bbd1aeac84481b1b7f6577c116/template.tpl#L128

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by m-karakus** [comment]
This is fixed with latest comment.
Thanks

**Comment by m-karakus** [comment]
@philpott can you please re-check and approve it please. 

İf everything looks good, can you please publish it on the GTM Template gallery.

Thank you.
