### ISSUE TITLE
Include/uncomment wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by philpott** [secureprivacy/secureprivacyai-gtm-template#2]
https://github.com/secureprivacy/secureprivacyai-gtm-template/blob/392f03eef94246bbd1aeac84481b1b7f6577c116/template.tpl#LL125C6-L125C21

When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by m-karakus** [comment]
Hi, this is fixed with new commit
